[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200

; Tregoni PlatformIO-s që libraritë e përbashkëta ndodhen direkt një nivel më lart (te folderi S3)
lib_extra_dirs = 
    ../

lib_deps =
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
