[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Shpejtësia e komunikimit serial
monitor_speed = 115200

; Lidhja relative me folderin e përbashkët të librarive tona Infokom
lib_extra_dirs = ../Infokom.MCU.ESP32.S3.Sensors

; Libraritë third-party që PlatformIO i menaxhon vetë
lib_deps =
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
